create database customer_shopping_behaviour;
use customer_shopping_behaviour;
select * from customers;

-- Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount)
from customers
group by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, discount_applied, sum(purchase_amount) as total_spent from customers
where discount_applied="Yes"
group by customer_id
having sum(purchase_amount)>(select avg(purchase_amount) from customers);

-- Q3. Which are the top 5 products with the highest average review rating?
with product_average_review as(
select item_purchased, round(avg(review_rating), 2) as average_rating,
dense_rank() over(order by avg(review_rating) desc) as d_rnk
from customers
group by item_purchased)
select item_purchased, average_rating
from product_average_review
where d_rnk<=5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, round(avg(purchase_amount), 2) as average_purchase_amt
from customers
where shipping_type in ("Standard", "Express")
group by shipping_type;

/* Q5. Do subscribed customers spend more? Compare average spend and total revenue 
   between subscribers and non-subscribers.*/
select subscription_status, count(*) as total_customers, round(avg(purchase_amount), 2) as average_spend,
round(sum(purchase_amount), 2) as total_revenue 
from customers
group by subscription_status;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
round(100 * sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) AS discount_rate
from customers
group by item_purchased
order by discount_rate desc
limit 5;

/* Q7. Segment customers into New, Returning, and Loyal based on their total 
   number of previous purchases, and show the count of each segment. */
with cust_segment as
(
select customer_id, previous_purchases,
case 
	when previous_purchases=1 then 'New'
    when previous_purchases between 2 and 10 then 'Returning'
    else 'Loyal'
    end as customer_segment
from customers
)
select customer_segment, count(*) as customer_count
from cust_segment
group by customer_segment
order by customer_count desc;

-- Q8. What are the top 3 most purchased products within each category? 
with item_ordered as
(
select category, item_purchased, count(*) as total_orders,
dense_rank() over(partition by category order by count(*) desc) as d_rnk
from customers
group by category, item_purchased
)
select * from item_ordered where d_rnk<=3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status, count(*) as repeat_buyers
from customers
where previous_purchases > 5
group by subscription_status;

-- Q10. What is the revenue contribution of each age group? 
select age_group, round(sum(purchase_amount), 2) as revenue
from customers
group by age_group
order by revenue desc;
